final List<String> genres = [
  'Antiques & Collectibles',
  'Architecture',
  'Art',
  'Bibles',
  'Biography & Autobiography',
  'Body, Mind & Spirit',
  'Business & Economics',
  'Comics & Graphic Novels',
  'Computers',
  'Cooking',
  'Crafts & Hobbies',
  'Design',
  'Drama',
  'Education',
  'Family & Relationships',
  'Fiction',
  'Foreign Language Study',
  'Games & Activities',
  'Gardening',
  'Health & Fitness',
  'History',
  'House & Home',
  'Humor',
  'Juvenile Fiction',
  'Juvenile Nonfiction',
  'Language Arts & Disciplines',
  'Law',
  'Literary Collections',
  'Literary Criticism',
  'Mathematics',
  'Medical',
  'Music',
  'Nature',
  'Performing Arts',
  'Pets',
  'Philosophy',
  'Photography',
  'Poetry',
  'Political Science',
  'Psychology',
  'Reference',
  'Religion',
  'Science',
  'Self-help',
  'Social Science',
  'Sports & Recreation',
  'Study Aids',
  'Technology & Engineering',
  'Transportation',
  'Travel',
  'True Crime',
  'Young Adult Fiction',
  'Young Adult Nonfiction',
];
